version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "org.jdom:jdom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.github.samtools:htsjdk"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
