/* Copyright Nabil Alikhan. 2010.
 * This file is part of BLAST Ring Image Generator (BRIG).
 * BRIG is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * BRIG is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 *  along with BRIG.  If not, see <http://www.gnu.org/licenses/>.
 */


package brig;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import javax.imageio.IIOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jdom.*;
import org.jdom.input.SAXBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author nabil
 */
public class QuickProfile extends javax.swing.JFrame {

    private static final Logger log = LoggerFactory.getLogger(QuickProfile.class);
    private static final String RESOURCE_PREFIX = "/brig/resources/profiles/";

    /** Creates new form QuickProfile */
    public QuickProfile() {
        initComponents();
        // Try filesystem first (legacy/dev), then classpath resources
        File prof = new File("profiles");
        if (prof.isDirectory()) {
            File[] list = prof.listFiles();
            if (list != null) {
                for (int i = 0; i < list.length; i++) {
                    if (!list[i].isHidden() && list[i].isFile() && !list[i].toString().endsWith(".jpg")) {
                        norings.addItem(list[i].getName());
                    }
                }
            }
        }
        if (norings.getItemCount() == 0) {
            // Load from classpath index
            try (InputStream idx = getClass().getResourceAsStream(RESOURCE_PREFIX + "profiles-index.txt")) {
                if (idx != null) {
                    BufferedReader br = new BufferedReader(new InputStreamReader(idx));
                    String line;
                    while ((line = br.readLine()) != null) {
                        line = line.trim();
                        if (!line.isEmpty()) {
                            norings.addItem(line);
                        }
                    }
                }
            } catch (IOException e) {
                log.error("Failed to load profiles index from classpath", e);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        norings = new javax.swing.JComboBox();
        jLabel75 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel87 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Load a template");
        if (BRIG.APP_ICON != null) setIconImage(BRIG.APP_ICON);

        norings.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                noringsItemStateChanged(evt);
            }
        });

        jLabel75.setText("Preset profile:");

        jButton2.setText("Save & close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel87.setText("jLabel87");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel75)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 145, Short.MAX_VALUE)
                .add(norings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButton2)
                .add(18, 18, 18)
                .add(jButton1)
                .add(55, 55, 55))
            .add(layout.createSequentialGroup()
                .add(38, 38, 38)
                .add(jLabel87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 488, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(norings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2)
                    .add(jLabel75)
                    .add(jButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 359, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noringsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_noringsItemStateChanged
        try {
            String selected = norings.getSelectedItem().toString();
            Image img = null;
            // Try filesystem first
            File doop = new File("profiles" + BRIG.SL + selected + ".jpg");
            if (doop.isFile()) {
                img = ImageIO.read(doop);
            } else {
                // Try classpath
                try (InputStream in = getClass().getResourceAsStream(RESOURCE_PREFIX + selected + ".jpg")) {
                    if (in != null) {
                        img = ImageIO.read(in);
                    }
                }
            }
            if (img != null) {
                Image newimg = img.getScaledInstance(400, 400, java.awt.Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(newimg);
                jLabel87.setIcon(icon);
                jLabel87.setText("");
            } else {
                jLabel87.setIcon(null);
                jLabel87.setText("No preview image could be found.");
            }
        } catch (IIOException e) {
            jLabel87.setIcon(null);
            jLabel87.setText("No preview image could be found.");
        } catch (Exception e) {
            log.error("Failed to load profile preview image", e);
        }
    }//GEN-LAST:event_noringsItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String selected = norings.getSelectedItem().toString();
        try {
            SAXBuilder builder = new SAXBuilder();
            Document temp = null;
            // Try filesystem first
            File get = new File("profiles" + BRIG.SL + selected);
            if (get.isFile()) {
                try {
                    temp = builder.build(get.getPath());
                } catch (JDOMException | IOException e) {
                    // Fall through to classpath attempt
                }
            }
            // Try classpath
            if (temp == null) {
                try (InputStream in = getClass().getResourceAsStream(RESOURCE_PREFIX + selected)) {
                    if (in != null) {
                        temp = builder.build(in);
                    }
                }
            }
            if (temp == null) {
                JOptionPane.showMessageDialog(this,
                        "Could not find profile: " + selected,
                        "ERROR!",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (temp.getRootElement().getAttributeValue("legendPosition") != null) {
                log.debug("Legend position: {}", temp.getRootElement().getAttributeValue("legendPosition"));
                BRIG.PROFILE.getRootElement().setAttribute("legendPosition", temp.getRootElement().getAttributeValue("legendPosition"));
                if (temp.getRootElement().getChild("cgview_settings") != null) {
                    BRIG.PROFILE.getRootElement().removeChild("cgview_settings");
                    Element cop = temp.getRootElement().getChild("cgview_settings");
                    cop.detach();
                    BRIG.PROFILE.getRootElement().addContent(cop);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,
                            selected + " uses an out of date format",
                            "ERROR!",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        selected + " uses an out of date format",
                        "ERROR!",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (JDOMException e) {
            JOptionPane.showMessageDialog(this,
                    selected + " is corrupt because :\n" + e.getMessage(),
                    "ERROR!",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "This is not a valid save file " + e.getMessage(),
                    "ERROR!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuickProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JComboBox norings;
    // End of variables declaration//GEN-END:variables

}
